development:
  secret_key_base: 9ac2d0ad8ebcc312090e99d745006d3cf8
  http_validation_key: N0T_S0_S3CR3ET

test:
  secret_key_base: a1580ad61ccb6ac60f9f256948cf63d6e20
  http_validation_key: N0T_S0_S3CR3ET

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  http_validation_key: <%= ENV["HTTP_VALIDATION_KEY"] %>